#!/bin/sh
# install-agent.sh — one-liner NexusMesh node installer.
#
#   curl -fsSL https://raw.githubusercontent.com/Kodjaoglanian/NetStream/main/scripts/install-agent.sh | \
#       sudo sh -s -- --server http://<SERVER>:8080 --authkey nexus_sec_...
#
# Options:
#   --server <URL>    control-plane base URL (required)
#   --authkey <KEY>   registration key nexus_sec_... (required first join)
#   --name <NAME>     node name (default: hostname)
#   --port <PORT>     UDP listen port (default: 51820)
# Env: NEXUS_VERSION=v0.1.0 to pin a release.
set -eu

REPO="Kodjaoglanian/NetStream"
VERSION="${NEXUS_VERSION:-latest}"
SERVER=""
AUTHKEY=""
NAME=""
PORT="51820"

while [ $# -gt 0 ]; do
    case "$1" in
        --server)  SERVER="$2"; shift 2 ;;
        --authkey) AUTHKEY="$2"; shift 2 ;;
        --name)    NAME="$2"; shift 2 ;;
        --port)    PORT="$2"; shift 2 ;;
        *) echo "unknown arg: $1" >&2; exit 1 ;;
    esac
done

say() { printf '\033[1;34m[nexus]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[nexus] error:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" = 0 ] || die "run as root (sudo sh -s -- ...)"
[ -n "$SERVER" ]  || die "missing --server <URL>"
[ -n "$AUTHKEY" ] || die "missing --authkey <nexus_sec_...>"

arch="$(uname -m)"
case "$arch" in
    x86_64|amd64)  TARGET="x86_64-unknown-linux-musl" ;;
    aarch64|arm64) TARGET="aarch64-unknown-linux-musl" ;;
    *)             die "unsupported architecture: $arch" ;;
esac

if [ "$VERSION" = "latest" ]; then
    tag="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" \
        | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1)"
    [ -n "$tag" ] || die "could not resolve latest release tag"
else
    tag="$VERSION"
fi
say "installing NexusMesh $tag ($TARGET)"

archive="nexusmesh-${tag}-${TARGET}.tar.gz"
base="https://github.com/$REPO/releases/download/$tag"
work="$(mktemp -d /tmp/nexusmesh.XXXXXX)"
trap 'rm -rf "$work"' EXIT

curl -fsSL "$base/$archive"        -o "$work/pkg.tar.gz"
curl -fsSL "$base/$archive.sha256" -o "$work/pkg.tar.gz.sha256"
(cd "$work" && sha256sum -c pkg.tar.gz.sha256 >/dev/null) || die "checksum failed"
tar -xzf "$work/pkg.tar.gz" -C "$work"

install -m 0755 "$work/bin/nexus-agent" /usr/local/bin/nexus-agent
install -m 0755 "$work/bin/nexus"       /usr/local/bin/nexus
if [ -f "$work/bin/nexus-tui" ]; then
    install -m 0755 "$work/bin/nexus-tui" /usr/local/bin/nexus-tui
fi

# --- config + keys --------------------------------------------------------
mkdir -p /etc/nexus
chmod 700 /etc/nexus
# Keys are generated by the agent on first start; write a minimal config so
# the unit starts with the right server/authkey.
cat > /etc/nexus/config.json <<EOF
{
  "server_url": "$SERVER",
  "authkey": "$AUTHKEY",
  "name": "${NAME:-$(hostname)}",
  "listen_port": $PORT
}
EOF
chmod 600 /etc/nexus/config.json

# --- systemd ---------------------------------------------------------------
if [ -f "$work/packaging/nexus-agent.service" ]; then
    install -m 0644 "$work/packaging/nexus-agent.service" /etc/systemd/system/nexus-agent.service
else
    cat > /etc/systemd/system/nexus-agent.service <<'UNIT'
[Unit]
Description=NexusMesh node agent
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
EnvironmentFile=-/etc/nexus/agent.env
ExecStart=/usr/local/bin/nexus-agent
Restart=on-failure
RestartSec=3
NoNewPrivileges=yes
PrivateTmp=yes
ProtectHome=yes
[Install]
WantedBy=multi-user.target
UNIT
fi

systemctl daemon-reload
systemctl enable --now nexus-agent
sleep 1
systemctl --no-pager --quiet is-active nexus-agent \
    || die "nexus-agent failed to start — check: journalctl -u nexus-agent"

# Bring the tunnel up now (the daemon re-registers automatically using the
# saved authkey in /etc/nexus/config.json).
nexus up --server "$SERVER" --authkey "$AUTHKEY"

say "done — node joined the mesh"
nexus status || true
